services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
      TZ: America/Sao_Paulo
    command: [ "postgres", "-c", "timezone=America/Sao_Paulo" ]
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: chatdb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: